---
title: "Research"
listing:
  - id: acad
    contents: posts
    include:
      categories: "Published"       # only items with this category
    sort: "date desc"
    type: default
  - id: nonacad
    contents: posts
    include:
      categories: "Working in progress"
    sort: "date desc"
    type: default
page-layout: full
title-block-banner: true
---

# Academic research

## Publication peer-reviewed

-   [**Natural Disasters And Individual Economic Performance: A Case Study From The Slave Lake Wildfire**](https://www.worldscientific.com/doi/abs/10.1142/S2010007825500125)\
    with [Nicholas Rivers](https://uniweb.uottawa.ca/view/profile/members/969?lang=en) and [Catherine Deri Armstrong](https://uniweb.uottawa.ca/view/profile/members/822?lang=en)

    [Climate Change Economics](https://www.worldscientific.com/doi/abs/10.1142/S2010007825500125 "NATURAL DISASTERS AND INDIVIDUAL ECONOMIC PERFORMANCE: A CASE STUDY FROM THE SLAVE LAKE WILDFIRE")\
    `Natural hazard, wildfire, income, Slave Lake`\
    In May 2011, the municipality of Slave Lake, Alberta, was hit by a devastating wildfire; the second costliest natural disaster in Canada at the time. Residents of Slave Lake were forced to evacuate for at least a month. This case study uses longitudinal income tax data from 2004 to 2018 to estimate the short, medium, and long-term individual economic effects of this wildfire. Estimates suggest an average drop in total income of 10.5% relative to a counter-factual scenario with no wildfire over the 7 years following the wildfire, mainly driven by a decrease in employment income. The percentage of total income lost is similar for males and females. The largest effects are found for workers in the agriculture and forestry sectors. Back-of-the- envelope calculations suggest an aggregate loss in employment income of \$150 million in the 7 years following the disaster, equivalent to over 13% of direct economic losses due to property damage, firefighting, and contemporaneous business closure.

    [SSRN Working Paper](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4333191)

-   [**Manufacturing output and extreme temperature: Evidence from Canada**](https://onlinelibrary.wiley.com/doi/abs/10.1111/caje.12633)\
    with [Nicholas Rivers](https://uniweb.uottawa.ca/view/profile/members/969?lang=en)\
    [Canadian Journal of Economics](https://onlinelibrary.wiley.com/doi/full/10.1111/caje.12633)\
    `Extreme temperature, climate change, manufacturing, Canada`\
    This paper analyzes the effects of extreme temperature on manufacturing output using a data set covering the universe of manufacturing establishments in Canada from 2004 to 2012. Extreme temperature can affect manufacturing activity directly through its impact on labour productivity and indirectly through a change in demand for products. Using a panel fixed effects method, our results suggest a non-linear relationship between outdoor extreme temperature and manufacturing output. Each day where outdoor mean temperatures are below  °C or above 24 °C reduces annual manufacturing output by 0.18% and 0.11%, respectively, relative to a day with mean temperature between 12 ° and 18 °C. In a typical year, extreme temperatures, as measured by the number of days below  °C or above 24 °C, reduce annual manufacturing output by 2.2%, with extreme hot temperatures contributing the most to this impact. Given the predicted change in climate for the mid- and end of century, we predict annual manufacturing output losses due to extreme temperature to range between 2.8% and 3.7% in mid-century and 3.7% and 7.2% in end of century.

    [University of Ottawa Economic Working Paper](https://ideas.repec.org/p/ott/wpaper/2006e.html)

-   [**Determination of Quebec's Quarterly Real GDP and Analysis of the Business Cycle, 1948–1980**](https://link.springer.com/article/10.1007/s41549-022-00077-7)\
    with [Mario Fortin](https://link.springer.com/article/10.1007/s41549-022-00077-7#auth-Mario-Fortin-Aff1), [Marcelin Joanis](https://link.springer.com/article/10.1007/s41549-022-00077-7#auth-Marcelin-Joanis-Aff2), [Philippe Kabore](https://link.springer.com/article/10.1007/s41549-022-00077-7#auth-Philippe-Kabore-Aff3) & [Luc Savard](https://link.springer.com/article/10.1007/s41549-022-00077-7#auth-Luc-Savard-Aff4).\
    [Journal of Business Cycle Research](https://link.springer.com/journal/41549)\
    `GDP, economic history, Quebec, Canada`\
    This study aims to consolidate the economic history of Quebec over the period from 1948 to 2019 with the emphasis on the period 1948–1980 for which we estimated the quarterly GDP for the province. Unlike previous economic studies relating to this period, we identify the chronology of the economic cycle of Quebec by estimating the real quarterly GDP by using the method of Ginsburgh (Appl Stat 22(3):368–374, 1973) as modified by De Carufel and Lizotte (in: Paper presented at Congrès de la Société canadienne de Science Économique, Montréal, 1982). Our analysis of the duration and intensity of recessions confirms the presence of regional cycles in Canada. Il shows also that the business cycle of Quebec is more strongly correlated with the US cycle than with the cycle in the rest of Canada for the period prior to 1980 and more correlated to the cycle of the rest of Canada onwards. We provide insights on why this trend changed over time.

-   [**How Do Carbon Taxes Affect Emissions? Plant-level Evidence from Manufacturing**\
    ](https://link.springer.com/article/10.1007/s10640-022-00678-x)with [Younes Ahmadi](https://link.springer.com/article/10.1007/s10640-022-00678-x#auth-Younes-Ahmadi-Aff1), [Akio Yamazaki](https://link.springer.com/article/10.1007/s10640-022-00678-x#auth-Akio-Yamazaki-Aff1-Aff2) & [Philippe Kabore](https://link.springer.com/article/10.1007/s10640-022-00678-x#auth-Philippe-Kabore-Aff3) .\
    [*Environmental and Resource Economics*](https://link.springer.com/journal/10640)\
    `Carbon Tax, Pollution, Manufacturing, Canada`\
    This paper investigates how carbon taxes affect emissions by examining British Columbia’s revenue-neutral carbon tax in the manufacturing sector. We theoretically demonstrate that carbon taxes can achieve emission reductions while increasing production. Recycling carbon tax revenues to lower corporate income tax rates encourages investments, allowing plants to emit less per unit of output. Using detailed confidential plant-level data, we evaluate this theoretical prediction by exploiting the treatment intensity through plants’ emission intensity. We find that the carbon tax lowers emissions by 4 percent. Furthermore, we find that the policy had a positive output effect and negative emission intensity effect, suggesting that the carbon tax encouraged plants to produce more with less energy. We provide initial evidence showing how a revenue-neutral carbon tax may achieve emission reductions while stimulating the economy.

## Work in progress

-   [**Does ESG adoption improve public traded companies' performance?**](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5385737)\
    with [**Nabil Afodjo**](https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=5654309 "View other papers by this author")and **[Ali Ghali](https://papers.ssrn.com/sol3/cf_dev/AbsByAuth.cfm?per_id=7839904 "View other papers by this author")**.\
    `ESG scores, firm performance, public traded company, sustainability`\
    Short description of the idea, data, and methods.
-   [**Voluntary Energy Program and Environmental-Economic Performance: Evidence from Manufacturing Sector in Canada**](https://drive.google.com/file/d/11GorrHQ6WrycL5iPe8dqP94FfxiVmGRt/view?usp=sharing)\
    with [Nicholas Rivers](https://uniweb.uottawa.ca/view/profile/members/969?lang=en).\
    `Voluntary program, energy conservation, manufacturing, Canada`\
    How do firms in the manufacturing sector respond to voluntary energy conservation program? Using data covering the universe of manufacturing firms in Canada over the period 2004 to 2012, we estimate the effectiveness of the Canadian Industry Program for Energy Conservation, the flagship federal government energy conservation program targeted at large industrial firms. We use a difference-in-difference approach, coupled with coarsened exact matching, to estimate the effect of this program on firms’ energy intensity, total productivity, as well as total energy and total output. Our estimation results suggest that the program does not significantly affect the energy intensity of participating firms compared to non-participating firms.
-   [**STAR: a transposition of the PICO framework to environmental sciences, engineering and beyond**](https://www.researchsquare.com/article/rs-6475550/v1)\
    with Paul Celicourt, Jacob Drapeau, Herlest B. Lovince, Stevens Azima, Cheikh M. M. Thiaw, Louis R. E. Asie, Louiné Célicourt, Fractyl Mertilus, Madoche Jean Louis, Alou T. Said, Harry J. Chery, Yonel Petit-Homme, Guensly Jn Pierre, Alain N. Rousseau, and Silvio Gumiere.\
    `Literature review, search strategy, search keywords, research questions, evidence synthesis, systematic search`\
    The formulation of research questions and the search of relevant bibliographical references are critical steps in the pursuit of evidence-based research. This process ought to be comprehensive, transparent, and reproducible. Furthermore, it must lead to the retrieval of a maximum number of potentially related articles that are subsequently analyzed to identify those that are effectively relevant. However, in environmental sciences, these tasks are often performed without an enabling systematic framework, but relying instead on an assembly of keyword strings and ‘regular expressions’ structured as a Boolean equation. This ad hoc approach often yields an incomplete and inconsistent search of the literature, which undermines the reliability of evidence syntheses. To address this gap, we introduce STAR, a System-Trouble/Treatment-Alternative-Response framework spun off the PICO (Population, Intervention, Comparison, Outcome) framework. STAR is well suited to perform evidence-based literature reviews in environmental sciences supported by robust bibliographical search strategies and research questions. In this paper, we detail the thinking process behind an effective application of STAR through several examples taken from different fields of environmental sciences and engineering (i.e., environmental informatics, hydroinformatics and sociohydrology, entomology and plant pathology, environmental sustainability, soil sciences, coastal sciences, and agrifood sciences).
